### ISSUE TITLE
[Bug]: This is not compatible with croustibat/filament-jobs-monitor plugin

### ISSUE THREAD

**Issue by asnever** [vstruhar/filament-failed-jobs#1]
### What happened?

The plugin id is the same as in croustibat/filament-jobs-monitor plugin. So that leads to conflict, and impossibility to use both of plugins. I think, it would be more logical to return something like this: 'filament-failed-jobs-monitor' here

### How to reproduce the bug

Use both croustibat/filament-jobs-monitor and vstruhar/filament-failed-jobs plugin

### Package Version

1.1.4

### PHP Version

8.3

### Laravel Version

11

### Which operating systems does with happen with?

Linux

**Comment by vstruhar** [comment]
Good catch, somehow I missed that... fixed in the latest release! 🚀

**Comment by asnever** [comment]
That works
Thanks!
